import type { Metadata, Viewport } from "next";
import { MiniKitWrapper } from "@/components/providers/MiniKitWrapper";
import { Toaster } from "@worldcoin/mini-apps-ui-kit-react";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" });

const BASE_URL = "https://turingvote.vercel.app";

const TITLE = "TuringVote — 5-question mirror for verified humans";
const DESCRIPTION =
  "Answer 5 quick this-or-that questions and see whether your choices land with the majority or minority among verified humans in World App.";

const STRUCTURED_DATA = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "TuringVote",
  url: BASE_URL,
  applicationCategory: "LifestyleApplication",
  operatingSystem: "World App",
  description: DESCRIPTION,
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
  featureList: [
    "5 quick this-or-that questions",
    "majority or minority mirror",
    "verified-human preference splits",
    "World ID / World App sign-in",
    "no rewards, streaks, betting, or leaderboard",
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: TITLE,
    template: "%s | TuringVote",
  },
  description: DESCRIPTION,
  alternates: {
    canonical: BASE_URL,
  },
  keywords: [
    "TuringVote",
    "5-question mirror",
    "this or that questions",
    "would you rather",
    "majority or minority",
    "World ID",
    "World App",
    "Mini App",
    "verified humans",
    "proof of personhood",
    "2-choice poll",
    "human vote",
  ],
  authors: [{ name: "TuringVote" }],
  creator: "TuringVote",
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: ["ja_JP"],
    url: BASE_URL,
    siteName: "TuringVote",
    title: TITLE,
    description: DESCRIPTION,
    // 2026-05-29 — branded 1200x630 share image (public/og.png, generated by
    // scripts/gen_og_image.py). Previously absent, so shared links rendered
    // with no preview and earned few clicks. metadataBase (BASE_URL) makes
    // the relative path resolve to an absolute URL.
    images: [
      {
        url: "/og.png",
        width: 1200,
        height: 630,
        alt: "TuringVote — answer 5 this-or-that questions and see your majority or minority mirror among verified humans.",
      },
    ],
  },
  twitter: {
    // summary_large_image gives the big banner preview on X (vs the small
    // square "summary"). Pairs with the og.png above.
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og.png"],
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
  themeColor: "#0A0A0A",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable, geistMono.variable)}>
      <head>
        {/* Preconnect to Supabase to shave ~100-300ms off the first /api call */}
        <link rel="preconnect" href="https://wgszbxgsxekwdmssnvvd.supabase.co" />
        <link rel="dns-prefetch" href="https://wgszbxgsxekwdmssnvvd.supabase.co" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(STRUCTURED_DATA) }}
        />
      </head>
      <body>
        <MiniKitWrapper>
          {children}
          <Toaster />
        </MiniKitWrapper>
        {/*
         * 2026-05-27 — Vercel Analytics + Speed Insights.
         * Analytics: page views + referrers + (eventually) custom events.
         * Speed Insights: Core Web Vitals (LCP / CLS / INP) from real users.
         *
         * Both ship client-side scripts that auto-detect the Vercel deployment
         * context. No env vars needed; the dashboard at vercel.com/<scope>/
         * <project>/analytics + /speed-insights populates within ~24h.
         *
         * Privacy: both products are anonymous by default (no PII, no cookies
         * unless the user explicitly enables identified analytics, which we
         * do not). This is intentionally compatible with TuringVote's
         * privacy posture (no tracking, no fingerprinting).
         */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
